### ISSUE TITLE
Structure of the main Repository

### ISSUE THREAD

**Issue by oke-aditya** [madewithml/hacktoberfest#2]
How should the repository be structured?

## Pitch 1

Something like
```
src (name better)
====> Machine Learning
====> Deep Learning
=======> DL-CV
=======> DL-NLP
====> Reinforcement Learning
====> Computer Vision
====> NLP
```

cc @ayulockin

**Comment by GokuMohandas** [comment]
Do you want to keep `CV` and `DL-CV` separate because of tasks that involve traditional CV approaches?

I was initially thinking efforts will either be application (`named-entity-recognition`) OR algorithm (`graph-neural-networks`) OR approach (`self-supervised-learning`) oriented but this won't adequately capture all efforts because something can easily fall in multiple categories. One option is to place it in all three subdirectories but that sounds a bit noisy. 

What type of work do you anticipate people to be participating in? If you think most people will be doing application oriented work, then we can simplify this. But I imagine some people will just want to tinker around with architectural changes, etc.

**Comment by oke-aditya** [comment]
I guess its bit tricky. The above approach is also good, let me improvise the above pitch. I think let the contributors and contributions grow. Then we can probably redesign to balance the files per folder ratio.

## Pitch 1.2

New names welcome 😃 

```
src (name better)
====> Machine Learning
-----------> Most sklearn stuff
-----------> Some Bayesian stuff

====> Deep Learning

=======> DL-CV
-------------------> Image classification
-------------------> Segmentation

=======> DL-NLP
---------------> Text Classification.
---------------> Text Summarization.
---------------> Text Embeddings.
---------------> Question Answering.

====> Reinforcement Learning
-----------> Traditional Methods
-----------> Deep Reinforcement Learning (A3C, etc)

====> Traditional Computer Vision
----------> Feature Extraction.
----------> Traditional Object Tracking / Detection
---------->

====> Traditional NLP
------------> Tf-idf
------------> NER
------------> POS Tagging
------------> NLTK stuff

```

Again I feel this way we can go for now there can be multiple such approaches.
E.g. Based on frameworks. Make folders for `tf, torch, keras, open-cv, nltk etc.`
Or as you said Task wise which is too possible but I still feel we should have a look at response from people and see how repository grows. Then we can balance it out.

**Comment by ayulockin** [comment]
Few pointers:
* The initial plan looks great. One minor thing that I would like to change is to rename `Traditional Computer Vision` to `Image Processing`.

* Is this repository for Hacktoberfest? If yes then we should put out a tweet about this and have a rule in the `CONTRIBUTING.md` which says to open an issue to submit the idea along with a quick bulleted summary of the deliverables. We can then organize them into folder and reply to the issue thread with the information where a PR should be made.(Even though the initial template looks great.)

* We should add few collab if we have any to kick this off. I have a thing or two that I can make a PR with.

* If the repository is meant to be around for community then also the approach of going out makes sense to me. I am open to suggestions here though.

**Comment by oke-aditya** [comment]
Above points are really good. Let me just create the folders from these and our discussion.
Currently every folder will just have `Readme.md` and that will tell what goes in that folder.
